# Utilise l'image de base Python 3.9
FROM python:3.9-slim

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie le fichier Python et les dépendances
COPY . .

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0

# Installe les dépendances Python spécifiées dans le fichier requirements.txt
RUN pip install --no-cache-dir -r requirements_main.txt

# Exécute le script Python lorsque le conteneur démarre
CMD ["python", "main.py"]
